plugins:
  - jest

env:
   node: true
   es2021: true
extends:
  - airbnb-base
  - eslint:recommended
  - plugin:jest/recommended
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules: {
  no-multi-spaces: off,
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }],
  no-console: off,
  javascript.validate.enable": off,
  import/no-unused-modules: [error, {missingExports: false, unusedExports: true}]
}