plugins:
  - jest

env:
   node: true
   es2021: true
extends:
  - airbnb-base
  - eslint:recommended
  - plugin:jest/recommended
  - plugin:import/errors
  - plugin:import/warnings
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules: {
  
  no-console: off,
  import/extensions: 0,
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }],
  no-param-reassign: 0,
  prefer-destructuring: 0,
  import/prefer-default-export: 0
  
}